name: Usage of environment and secret

on:
  workflow_dispatch: 

jobs:
  use_develop:
    # This job only runs for pull request
    name: Use develop environment
    runs-on: ubuntu-latest
    environment:
      name:develop
    steps:
     if: ${{ secrets.ENVIRONMENT_NAME == 'develop' }}
      - name:
        run: echo Secret used from develop environment
     if: ${{ secrets.ENVIRONMENT_NAME == 'production' }}
      - name:
        run: echo Secret used from production environment
   use_production:
    # This job only runs for pull request
    name: Use develop environment
    runs-on: ubuntu-latest
    environment:
      name:production
    steps:
     if: ${{ secrets.ENVIRONMENT_NAME == 'develop' }}
      - name:
        run: echo Secret used from develop environment
     if: ${{ secrets.ENVIRONMENT_NAME == 'production' }}
      - name:
        run: echo Secret used from production environment
